### ISSUE TITLE
Support OTEL_RESOURCE_ATTRIBUTES environmental variable

### ISSUE THREAD

**Issue by dhpollack** [GoogleCloudPlatform/opentelemetry-operations-python#146]
I created a PR (#145) to support this environmental variable which is part of the OTEL specification.  I want to be able to add custom attributes to all spans of a specific service and this is the easiest way to do it.  The current resource attribute getter ignores these attributes and only gets gcp specific ones.

**Comment by aabmass** [comment]
Thanks for the PR! The `OTEL_RESOURCE_ATTRIBUTES` environment variable is already implemented in OpenTelemetry Python ([see these docs](https://opentelemetry-python.readthedocs.io/en/latest/sdk/environment_variables.html#opentelemetry.sdk.environment_variables.OTEL_RESOURCE_ATTRIBUTES)), so your PR doesn't need to implement that.

> I want to be able to add custom attributes to all spans of a specific service and this is the easiest way to do it.

I'm curious what kind of attributes you want to add, do they actually fit the model of a "[resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#resources)"?

> The current resource attribute getter ignores these attributes and only gets gcp specific ones.

This is true, we should probably pass the rest on as span attributes since Cloud Trace doesn't have a first-class resource concept right now. Just be aware that it will be a lot of repetitive information in your spans!

**Comment by dhpollack** [comment]
I wanted to initially add the name of the app via "service.name". We do something more manually with open census and middleware but this seems to make more sense because the information is already in the span, just not exported to gcp.  In the future I was thinking of using it to tag spans globally and do some A/B testing.

**Comment by aabmass** [comment]
Gotcha, service name definitely belongs in resource. What kind of GCP compute are you running this on btw? I think we should add this feature but probably it should be off by default and have an option in the exporter's constructor to enable it.

> In the future I was thinking of using it to tag spans globally and do some A/B testing.

This sounds more like [baggage](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#baggage-signal) is what you want here, to propagate extra key values between services. It's still not 100% clear how baggage makes it way into a span https://github.com/open-telemetry/opentelemetry-specification/issues/867, but you could write a span processor to modify the span based on the [parent context](https://github.com/open-telemetry/opentelemetry-python/blob/2098c5644588cd4e766eb8e31a1ca26c4e00ea46/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L84).

**Comment by dhpollack** [comment]
I think it's more that if I add a resource with the otel environmental variable, I expect to see it. I agree what I'm doing with this feature could be misguided but I need to figure that out on my own. :-)

I ended up spending hours with this until I used the console exporter and realized the data was added to the span but not to the data uploaded to Google.

**Comment by aabmass** [comment]
@dhpollack let do this:

> I think we should add this feature but probably it should be off by default and have an option in the exporter's constructor to enable it.

I'll comment on your PR
