### ISSUE TITLE
Cloud Trace exporter adds seconds of latency to HTTP requests

### ISSUE THREAD

**Issue by askmeegs** [GoogleCloudPlatform/opentelemetry-operations-python#75]
Hello, I work on the [Bank of Anthos](https://github.com/GoogleCloudPlatform/bank-of-anthos) sample application. In July, we added the OpenTelemetry exporter and trace propagator to 3 Python services (all using flask/gunicorn, all running inside containers on GKE). 

We have determined that the OT exporter seems to be causing multiple seconds of latency per request ([findings here](https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/356)). [We upgraded OT to the latest version](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/360) (`0.13b0`) but we're still seeing latency in the app.
  
My hypothesis is that there is a process in the exporter that is slow on a per-request basis, or there is something going on with our GKE environment/Trace API authentication that is causing the latency.  

Wondering if you've seen anything similar, or are doing any performance testing on these libraries. Thank you!

**Comment by aabmass** [comment]
@askmeegs from the PR, it looks like you are using [`SimpleExportSpanProcessor`](https://opentelemetry-python.readthedocs.io/en/stable/sdk/trace.export.html#opentelemetry.sdk.trace.export.SimpleExportSpanProcessor)? This processor really slows things down because it runs all of the export calls synchronously without any batching.

Try [`BatchExportSpanProcessor`](https://opentelemetry-python.readthedocs.io/en/stable/sdk/trace.export.html#opentelemetry.sdk.trace.export.BatchExportSpanProcessor) instead and that resolve your latency issues:

```py
trace.get_tracer_provider().add_span_processor(
    BatchExportSpanProcessor(exporter)
)
```

**Comment by askmeegs** [comment]
Thank you for this suggestion, Aaron! I switched the 3 python services to use the `BatchExportSpanProcessor` and that seems to have fixed the latency issue. Closing this issue. Thanks!
